services:
  washing_machines_iot:
    image: washing_machines_iot_server_lite
    hostname: washing_machines_iot
    restart: always
    container_name: washing_machines_iot
    ports:
      - 49152:8000
    networks:
      - mongo-network
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo
    hostname: mongodb
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - mongo-network
    healthcheck:
      test: $$(echo "rs.initiate().ok || rs.status().ok" | mongosh --quiet | grep -q "already initialized") && test "$?" -eq 0
      interval: 10s
      start_period: 30s
    command: [ "--replSet", "dbrs", "--bind_ip_all"]
networks:
  mongo-network:
    driver: bridge